# frozen_string_literal: true

# Gemfile

source 'https://rubygems.org' do
  gem 'aws-sdk-lambda', '1.39.0'
  gem 'aws-sdk-s3'
  gem 'aws-xray-sdk', '0.11.4'
  gem 'rubocop', group: 'development'
  gem 'test-unit', '3.3.5'
end
